### ISSUE TITLE
Ionic New Project Failing

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/brightlayer-ui-cli#111]
#### Describe the bug
Cannot create a new ionic authentication template with prettier & eslint enabled. 

#### What is the expected behavior?
It works.

#### What are the steps to reproduce?
1. `npx -p @pxblue/cli@ pxb new` and select ionic, prettier, auth, eslint options. 

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/6538289/146260092-ea614923-b550-421c-9248-4bf786f69be1.png)

#### Anything else to add?
Windows

**Comment by joebochill** [comment]
Since we're planing to drop official support for Ionic, we don't need to worry about ionic issues.
