### ISSUE TITLE
Be More Specific on how to use Templates

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/brightlayer-ui-cli#113]
#### Describe the desired behavior
Templates have to `blank` `routing` or `authentication`

#### Describe the current behavior
Docs do not mention this and can be interpretted as the package used instead.

#### Is this request related to a current issue?
No

**Comment by joebochill** [comment]
You mean like this table in the README?
![image](https://user-images.githubusercontent.com/29152776/147663345-2177b5c4-b18e-47f8-99b5-bf0043a6aad2.png)

**Comment by jeffvg** [comment]
lets do some word smithing on item 2 to be more specific on template and not seem like its the package name.

![image](https://user-images.githubusercontent.com/37150565/148392063-2cde09c5-e803-4cf7-bdc4-81a93d25fd6a.png)
