### ISSUE TITLE
Update dependencies and resources

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/brightlayer-ui-cli#116]
#### Describe the desired behavior
Use Angular 13, React 17, MUI v5 and update other dependencies used by the CLI

#### Describe the current behavior
These dependencies are out of date

#### Is this request related to a current issue?
No

#### Additional Context

Some of these dependencies may already be handled by updates to the templates themselves, but we should check to see what else there is that is specified in the CLI and need to be updated.

**Comment by emclaug2** [comment]
Make sure to use the @brightlayer-ui/eslint-config@3.0.0 and update all required deps.

**Comment by emclaug2** [comment]
Fixed in #126
