### ISSUE TITLE
RN Android instructions missing step

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/brightlayer-ui-cli#132]
#### Describe the bug
After the CLI runs, when printing the instructions for running on Android, the `cd` step is missing.

#### What is the expected behavior?
The first step in the Android instructions should be to `cd` into the project directory we just created.

The instructions should be:
- Have an Android emulator running
- cd <project-folder>
- yarn android

#### What are the steps to reproduce?

1. clone this repository
2. `yarn && yarn build && yarn link`
3. `blui new react-native`
4. Respond to the prompts to create a new react native project
5. After the project is created, observe the printed instructions for Android. The `cd` step into the project is missing.

#### Screenshots or links to minimum reproduction example

<img width="286" alt="image" src="https://user-images.githubusercontent.com/29152776/172365331-6101b5df-5941-4ca9-be6a-be9c99a07ea8.png">
		
#### Anything else to add?

The instructions are correct for running on iOS. We should be able to reference that in order to make this update.

**Comment by AlanLes** [comment]
Can I please take this issue? I've already created a PR :)
