### ISSUE TITLE
Enforce Valid Template Selection

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/brightlayer-ui-cli#52]
#### Describe the desired behavior
CLI template selection should be limited to supported templates.  This applies to angular and react projects. 

#### Describe the current behavior
Users can enter whatever template they want through the `--template` flag.

#### Is this request related to a current issue?
No

**Comment by emclaug2** [comment]
If template name does not exist, it defaults to the blank template.

**Comment by emclaug2** [comment]
If template name is not valid, show a prompt with multiple choices where user can select a valid template.

**Comment by joebochill** [comment]
How do we determine what is a valid template? Is is `authentication | routing | blank | <any local template file that matches a file:// regex>`? Are we going to validate that a local file template exists and is valid? I would lean towards allowing anything that starts with the local file prefix (for testing purposes) or one of the preconfigured strings. If it's not a match for that, show the prompt for the template (same as if they had not specified a template at all).
