### ISSUE TITLE
React Native template project tests fail

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/brightlayer-ui-cli#99]
#### Describe the bug
The default app-test for RN template projects fail due to not having safe-area wrapper for when the header is rendered in test.
![image](https://user-images.githubusercontent.com/37150565/130500433-7394db15-a777-411e-9d96-19a6ec1c0d7e.png)

#### What is the expected behavior?
test to pass with default test file
#### What are the steps to reproduce?
1. Start new RN blank project - npx -p @pxblue/cli pxb new
2. Open project and run yarn test

#### Anything else to add?
The issue can be fixed via the CLI project or in the templates repo.
The test file should have...
import { SafeAreaProvider } from 'react-native-safe-area-context';
- and with

![image](https://user-images.githubusercontent.com/37150565/130503091-c1e00232-83e4-415a-af37-16887ee63958.png)

**Comment by jeffvg** [comment]
We can fix it by either
1. wrapping the test in a SafeAreaProvider (as you suggested), which would probably need to be done in the CLI, or
2. mocking the useSafeAreaInsets hook (https://github.com/pxblue/react-native-component-library/blob/e75f5f00fa74dfa54f8ed03f626ef0a5f273915e/components/src/core/header/header.test.tsx#L9) this would also likely be done in the CLI instead of the templates
3. Put a SafeAreaProvider around our Header component (in our component library) so it always exists. Haven't tried that one, so I don't know what that would do 100%.

**Comment by jeffvg** [comment]
this solution would be best - Put a SafeAreaProvider around our Header component (in our component library) so it always exists. Haven't tried that one, so I don't know what that would do 100%.

**Comment by daileytj** [comment]
![Simulator Screen Shot - iPhone 12 - 2021-09-24 at 12 42 30](https://user-images.githubusercontent.com/13989985/134711149-0e444027-3085-4c3c-abc8-a117a46cdc13.png)
 This is the result of wrapping the header in SafeAreaProvider :(

**Comment by joebochill** [comment]
We tried wrapping the Header component and it didn't work as expected. It also goes against the recommendation in the safe area provider library to set it at the top of your application.

I believe we have added the SafeAreaProvider in all of our RN templates at this point, so is this still an issue?

If it is, we can do number 2 from above for a quick win that isn't quite as invasive as wrapping all of the tests in a provider.

**Comment by jeffvg** [comment]
verified all 3 react-native template projects tests pass

import 'react-native';
import React from 'react';
import App from '../App';

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

it('renders correctly', () => {
  renderer.create(<App />);
});

![image](https://user-images.githubusercontent.com/37150565/151988131-65ad39c2-5a9f-4838-9c2a-c918466c6d15.png)
